version: "3"

tasks:
  init:
    cmds:
      - git submodule init
      - git submodule update --init --recursive

  configure_debug:
    cmds:
      - cmake -B ./build -G {{.CLI_ARGS}} -DCMAKE_BUILD_TYPE=Debug

  configure_release:
    cmds:
      - cmake -B ./build -G {{.CLI_ARGS}} -DCMAKE_BUILD_TYPE=Release

  build_debug:
    cmds:
      - cmake --build ./build --config Debug --target {{.CLI_ARGS}}

  build_release:
    cmds:
      - cmake --build ./build --config Release --target {{.CLI_ARGS}}

  clean:
    cmds:
      - cmake --build ./build --target clean
